import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>home page</h1>
    </>
  )
}

function parseQueryStringToObject(queryString) {
  const decodedString = decodeURIComponent(queryString);
  return JSON.parse(decodedString.substring(decodedString.indexOf('{'), decodedString.lastIndexOf('}') + 1));
}



Home.getInitialProps = async (ctx) => {
  const { req, res } = ctx;
  const userData = await parseQueryStringToObject(req.headers.cookie);
  return { props: { userData } };
} 